### ISSUE TITLE
Setup: Endless loop when calling 'as'

### ISSUE THREAD

**Issue by bannsec** [shellphish/shellphish-afl#1]
Looks like there may be an issue when installing afl with the following error:

```
    [-] PROGRAM ABORT : ^[[1;37mEndless loop when calling 'as' (remove '.' from your PATH)^[[1;31m
             Location : ^[[0mmain(), afl-as.c:509

    Makefile:70: recipe for target 'afl-fuzz' failed
```

Technically this is coming from afl, so it's certainly something they need to look into as well. The problem here is that, at least on Ubuntu, the "as" command is provided by the common package `binutils`. This means that compiling won't work until you remove the binutils `as` instruction from your path. Not sure the best way to handle this programmatically, but it's causing build failures.

**Comment by bannsec** [comment]
Nevermind. I had an accidental "::" in my path var.

**Comment by hailinzeng** [comment]
Not relevant to this project, But I found adding the $AFL_HOME/bin to $PATH produce the same error.

**Comment by RenWal** [comment]
ZSH from the Ubuntu repos (5.4.2-3ubuntu3.1) causes this as well. Look in the ~/.zshrc file and remove the leading ':' from the path definition.

**Comment by JasonRabbit** [comment]
cd $AFL_HOME 
You can see that $AFL_HOME/as is exist, and it is conflict with /usr/bin/as。
Just remove the $AFL_HOME from the $PATH or rename $AFL_HOME/as to another name to avoid this problem.
