### ISSUE TITLE
an error when  pip install git+https://github.com/shellphish/shellphish-afl

### ISSUE THREAD

**Issue by leithon** [shellphish/shellphish-afl#3]
fakeforksrv.c:2:23: fatal error: sys/prctl.h: No such file or directory
    run_via_fakeforksrv.c:3:23: fatal error: sys/prctl.h: No such file or directory
    compilation terminated.
    compilation terminated.
    <builtin>: recipe for target 'fakeforksrv' failed
    make[1]: *** [fakeforksrv] Error 1
    make[1]: *** Waiting for unfinished jobs....
    <builtin>: recipe for target 'run_via_fakeforksrv' failed
    make[1]: *** [run_via_fakeforksrv] Error 1
    make[1]: Leaving directory '/tmp/pip-build-GCn4rm/shellphish-afl/bin/afl-multi-cgc/fakeforksrv'
    Makefile:2: recipe for target 'all' failed
    make: *** [all] Error 2
    error: Unable to make afl-multi-cgc

**Comment by zardus** [comment]
Looks like you're missing a bunch of packages. If you're on ubuntu, `sys/prctl.h` is in `libc6-dev`. In general, shellphish-afl has all the same requirements as building AFL itself.

**Comment by mcgrady1** [comment]
I have upgraded libc6-dev, it still didn't work.
make[1]: Entering directory `/tmp/pip-DpW3c7-build/bin/afl-multi-cgc/fakeforksrv'
cc -O3 -march=core2 -m32 -std=gnu99 -g -g3 -ggdb -gdwarf-4 -Wall -Wextra    fakeforksrv.c   -o fakeforksrv
cc -O3 -march=core2 -m32 -std=gnu99 -g -g3 -ggdb -gdwarf-4 -Wall -Wextra    run_via_fakeforksrv.c   -o run_via_fakeforksrv
run_via_fakeforksrv.c:3:23: fatal error: sys/prctl.h: No such file or directory
 #include <sys/prctl.h>
                       ^
fakeforksrv.c:2:23: fatal error: sys/prctl.h: No such file or directory
 #include <sys/prctl.h>
                       ^
compilation terminated.
compilation terminated.
make[1]: *** [fakeforksrv] Error 1
