### ISSUE TITLE
error in installing shellphish-afl

### ISSUE THREAD

**Issue by benquike** [shellphish/shellphish-afl#4]
I am trying to install this package on ubuntu 17.04

it seems that there is some issue with the keys when downloading
packages for armel. To be more specific, when executing 

```
fetcharch armel ubuntu precise
```
fetchlibs.sh

It emits the following error message"

```
I: Retrieving InRelease 
I: Failed to retrieve InRelease
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
gpgv: Signature made Wed 25 Apr 2012 06:49:42 PM EDT
gpgv:                using DSA key 
gpgv: Can't check signature: No public key
E: Release signed by unknown key (key id 40976EAF437D05B5)
```

**Comment by zardus** [comment]
That's an apt issue (as you probably know) -- looks like your signature-verification stuff isn't set up properly.

Good luck :-)

**Comment by bannsec** [comment]
Ran into the same issue (this is from a new install of Ubuntu 17.04). My guess is that, between 16.04 and 17.04 the keys for that were probably dropped from gpg archive (or expired?).

Also, according to this Ubuntu post, they don't and haven't supported armel for a while: https://bugs.launchpad.net/ubuntu/+source/rootstock/+bug/1317053

Good ol' Debian does indeed appear to have support. The fix I implemented was to change the armel line from using ubuntu to debian:

```
fetcharch armel debian jessie
```

I'll submit a PR. Given I don't really have full knowledge on how all this stuff works, perhaps this change breaks something? Will leave it up to the experts to approve my PR ;-)

PS: @zardus -- i'll be dropping by your CTF station at DEFCON. You should invite me to the l33t hacker parties I know you go to ;-)

**Comment by zardus** [comment]
Thanks! I merged the fix. If it breaks something, we sure as heck don't have testcases to catch it -- we only test fuzzing of CGC bins. Some simple testcases for other stuff would actually be very nice...

@Owlz, mis l337 hacker parties son sus l337 hacker parties, though I suspect you vastly overestimate my celebrity status :-)

@benquike, could you confirm that this was the issue you were running into?
